refactored hard coded indentation
saulmaldonado/dotenv-types-generator pull request #8
Opened 2020-10-05 09:20 UTC by yvz5

Fixes #1 

@saulmaldonado  Let me know what you think

2020-10-05 11:33 UTC, saulmaldonado requested changes
Your implementation for solving this issue is great and can wait to get it pulled. There are just some formatting issues that can be fixed to make it look a lot better. Read through the comments I've left.

Be sure to lint and format your changes as there some consistencies. If the pre-commit hook doesn't fire you can run `npm run lint __test__/**/*.js src/**/*.js` and `npm run prettier __test__/**/*.js src/**/*.js`. This will format and lint your files automatically wherever it can and output errors wherever it can't. Let me know if you run into any problems or have any questions!

2020-10-05 11:33 UTC, saulmaldonado commented on __test__/generate.test.js
> +'export {};\n';
Changes to the expected file template can be reverted. This will make it easier to read and easier to diff between output and expected files.

2020-10-05 11:33 UTC, saulmaldonado commented on __test__/index.test.js
> +'export {};\n';
This template can also be reverted

2020-10-05 11:33 UTC, saulmaldonado commented on __test__/index.test.js
> +'export {};\n';
This template can also be reverted.

2020-10-05 11:33 UTC, saulmaldonado commented on __test__/tpye-printer.test.js
> +							'export {};\n';
Expected files in new tests can also be converted to template literals
ex.
```js
const expected = `declare global {
  namespace NodeJS {
    interface ProcessEnv {
      VARIABLE1: string;
      VARIABLE2: string;
    }
  }
}
  
export {};
`;
```

2020-10-05 11:33 UTC, saulmaldonado commented on src/type-printer.js
> +    const indentation = indentationText.repeat(parseInt(element.indentation));
parseInt being used on a number. This can be removed.

`const indentation = indentationText.repeat(element.indentation);	`

2020-10-05 11:33 UTC, saulmaldonado commented on __test__/tpye-printer.test.js
> +import { printTypes } from '../src/type-printer';
typo in filename. This can be changed to `typePrinter.test.js`

2020-10-05 11:33 UTC, saulmaldonado commented on src/generate.js
> +import { printTypes } from './type-printer';
`type-printer` filename can be changed to `printTypes` to match the function name

2020-10-05 11:33 UTC, saulmaldonado commented on src/type-printer.js
> +const placeholderText = "types-placeholder";
rename filename from `type-printer.js` to `typePrinter.js`

2020-10-05 11:44 UTC, yvz5 commented on __test__/generate.test.js
> +'export {};\n';
this somehow fail the tests. The indentation also fails, thats why I have converted them. Could you try it locally to see if it only happens on my machine.

2020-10-05 11:55 UTC, yvz5 commented on __test__/generate.test.js
> +'export {};\n';
![image](https://user-images.githubusercontent.com/439370/95076620-6b8adb00-0712-11eb-8dd8-1292ba51ec50.png)
this is the result of npm test command when I revert back to template literal

2020-10-05 14:12 UTC, saulmaldonado commented on __test__/generate.test.js
> +'export {};\n';
@yvz5 I pulled down your PR on my local machine and found that the extra whitespace is caused from placing the template literal inside of the testing block. You are able to demote this extra indentation by using `SHIFT + TAB` but this causes some ugly alignment issues. I recommend placing it outside the testing blocks and like it is in the other testing files.

You can use the following to replace the `printTypes.test.js` file. Be sure to also revert the file templates in the other testing files. Everything else looks great!
```js
import { printTypes } from '../src/printTypes';

const expectedSize2 = `declare global {
  namespace NodeJS {
    interface ProcessEnv {
      VARIABLE1: string;
      VARIABLE2: string;
    }
  }
}

export {};
`;

const expectedSize4 = `declare global {
    namespace NodeJS {
        interface ProcessEnv {
            VARIABLE1: string;
            VARIABLE2: string;
        }
    }
}

export {};
`;

describe('printTypes tests', () => {
  it('should create correct indentation: size 2', () => {
    const data = ['VARIABLE1: string;', 'VARIABLE2: string;'];

    const output = printTypes(2, data);
    expect(output).toEqual(expectedSize2);
  });

  it('should create correct indentation: size 4', () => {
    const data = ['VARIABLE1: string;', 'VARIABLE2: string;'];

    const output = printTypes(4, data);
    expect(output).toEqual(expectedSize4);
  });
});

```

2020-10-05 14:12 UTC, saulmaldonado commented on __test__/generate.test.js
> +'export {};\n';
@yvz5 I pulled down your PR on my local machine and found that the extra whitespace is caused from placing the template literal inside of the testing block. You are able to demote this extra indentation by using `SHIFT + TAB` but this causes some ugly alignment issues. I recommend placing it outside the testing blocks and like it is in the other testing files.

You can use the following to replace the `printTypes.test.js` file. Be sure to also revert the file templates in the other testing files. Everything else looks great!
```js
import { printTypes } from '../src/printTypes';

const expectedSize2 = `declare global {
  namespace NodeJS {
    interface ProcessEnv {
      VARIABLE1: string;
      VARIABLE2: string;
    }
  }
}

export {};
`;

const expectedSize4 = `declare global {
    namespace NodeJS {
        interface ProcessEnv {
            VARIABLE1: string;
            VARIABLE2: string;
        }
    }
}

export {};
`;

describe('printTypes tests', () => {
  it('should create correct indentation: size 2', () => {
    const data = ['VARIABLE1: string;', 'VARIABLE2: string;'];

    const output = printTypes(2, data);
    expect(output).toEqual(expectedSize2);
  });

  it('should create correct indentation: size 4', () => {
    const data = ['VARIABLE1: string;', 'VARIABLE2: string;'];

    const output = printTypes(4, data);
    expect(output).toEqual(expectedSize4);
  });
});

```

2020-10-06 10:04 UTC, saulmaldonado approved these changes
Everything looks great! Thank you for taking the time to read my comments and make the improvements!

2020-10-06 10:04 UTC, merged